services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskwatch?schema=public
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules
      - web_next:/app/.next
    depends_on:
      - db
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]

  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskwatch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  web_node_modules:
  web_next:
